name: Compile LaTeX

on:
  push:
    paths:
      - 'latex/**/*.tex'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: latex/test.tex
